## Matrix product calculated manually

The matrix product of matrices A and B can be calculated manually using the following steps:

Multiply corresponding elements of the first row of matrix A with the first column of matrix B, and sum the products. Repeat this for all elements in the resulting matrix.


Matrix A:

-1  2  3

 4 -5  6

 7  8 -9


Matrix B:

 0  2  1

 0  2 -8

 2  9 -1

Matrix Product C:

(-1 * 0) + (2 * 0) + (3 *  2)    (-1 * 2) + (2 * 2) + (3 * 9)    (-1 * 1) + (2 * -8) + (3 * -1)

(4 * 0) + (-5 * 0) + (6 * 2)   (4 * 2) + (-5 * 2) + (6 * 9)    (4 * 1) + (-5 * -8) + (6 * -1)

(7 * 0) + (8 * 0) + (-9 * 2)   (7 * 2) + (8 * 2) + (-9 * 9)    (7 * 1) + (8 * -8) + (-9 * -1)


## Calculation by NumPy function

In [2]:
import numpy as np

# Define matrices A and B
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# Calculate matrix product using NumPy
c_ndarray = np.matmul(a_ndarray, b_ndarray)
c_ndarray

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## Implementation of calculation of a certain element

In [3]:
# Define matrices A and B
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# Calculate a certain element of the matrix product without using NumPy functions
c_00 = 0
for k in range(3):
    c_00 += a_ndarray[0, k] * b_ndarray[k, 0]

print("Element c_00 of the matrix product:", c_00)


Element c_00 of the matrix product: 6


## Creating a function that performs matrix multiplication

In [5]:
def matrix_product(a, b):
    # Initialize an empty matrix for the result
    c = np.zeros((a.shape[0], b.shape[1]))
    
    # Iterate through rows of A
    for i in range(a.shape[0]):
        # Iterate through columns of B
        for j in range(b.shape[1]):
            # Iterate through rows of B
            for k in range(b.shape[0]):
                c[i, j] += a[i, k] * b[k, j]
    
    return c

# Test the function
result_matrix = matrix_product(a_ndarray, b_ndarray)
result_matrix

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

## Judge the input whose calculation is not defined

In [7]:
def matrix_product_safe(a, b):
    if a.shape[1] != b.shape[0]:
        print("Matrix multiplication is not defined for the given input matrices.")
        return None
    else:
        return matrix_product(a, b)

# Test the function
result_matrix_safe = matrix_product_safe(a_ndarray, b_ndarray)
result_matrix_safe

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

## Transposition

In [8]:
# Transpose matrix B and calculate matrix product
b_transpose = np.transpose(b_ndarray)
c_transpose = matrix_product(a_ndarray, b_transpose)


In [9]:
b_transpose

array([[ 0,  0,  2],
       [ 2,  2,  9],
       [ 1, -8, -1]])

In [10]:
c_transpose

array([[  7., -20.,  13.],
       [ -4., -58., -43.],
       [  7.,  88.,  95.]])